"""
VMS Pro — FIR Evidence Report Generator

FRAUD-01 FIXES:
  - Removed fabricated SHA-256 hash (was hash of empty string — E3B0C44...)
  - Removed fake DigiCert TSA claim
  - Removed hardcoded "Badge #4521" (now shows user's actual username)
  - Removed hardcoded "VERIFIED MATCH" on all rows — now based on real Track data
  - FIR access restricted to operator+ (was viewer — COMP-04 fix)

COMP-04 FIX: Endpoint now requires verify_operator (was verify_viewer)

The digital integrity hash is now computed from real case metadata
including the export_id, generating user, timestamp, and audit log entry ID.
A real RFC-3161 TSA would require an external service; we honestly state
this is an internal server-signed timestamp, not a third-party TSA.
"""

import os
import re
import hashlib
import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from ..database.connection import get_db
from ..database.models import AuditLog, Camera, Alert, Track
from ..auth.helpers import verify_operator   # COMP-04 fix: was verify_viewer

router = APIRouter(prefix="/forensics", tags=["FIR Report"])


def _compute_case_hash(case_num: str, username: str, timestamp_iso: str, audit_id: int) -> str:
    """
    Computes a real SHA-256 hash over actual case metadata.
    This creates a verifiable fingerprint of WHO generated this report and WHEN.
    It is an internal integrity signature — not an RFC-3161 TSA (which requires
    an external timestamping authority; we do not claim to use one).
    """
    payload = f"{case_num}|{username}|{timestamp_iso}|audit#{audit_id}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest().upper()


@router.get("/fir-report/{export_id}", response_class=HTMLResponse)
def generate_fir_case_report(
    export_id: str,
    user=Depends(verify_operator),   # COMP-04 FIX: was verify_viewer — FIR requires operator+
    db: Session = Depends(get_db)
):
    """
    Generates a printable FIR Evidence Annexure with real cryptographic integrity signature.
    Access restricted to operators and administrators only.
    """
    from ..utils.timezone import get_ist_now
    now = get_ist_now()
    now_str = now.strftime("%Y-%m-%d %H:%M:%S IST")
    now_iso = now.isoformat()

    # BUG-12 FIX: Validate export_id is safe before embedding in HTML (prevents XSS via path param)
    if not re.match(r'^[A-Za-z0-9_\-]{1,64}$', export_id):
        raise HTTPException(status_code=400, detail="Invalid export_id format. Must be alphanumeric, hyphens, or underscores only.")

    case_num = f"FIR-2026-SURAT-{export_id.upper()}"

    from ..utils.audit import log_audit_event
    client_ip = getattr(user, "_client_ip", None)

    # Create audit log entry first so we can include its real ID in the hash
    audit_entry = log_audit_event(
        db,
        action="GENERATE_FIR_REPORT",
        detail=f"Case {case_num} generated by {user.username}",
        username=user.username,
        ip_address=client_ip,
    )
    audit_id = audit_entry.id

    # Compute real hash over actual metadata
    integrity_hash = _compute_case_hash(case_num, user.username, now_iso, audit_id)

    cams = db.query(Camera).all()

    # Build timeline rows — only show ACTUAL track data, not fabricated "VERIFIED MATCH"
    timeline_rows = ""
    for idx, cam in enumerate(cams):
        # Look for real tracks on this camera
        recent_tracks = (
            db.query(Track)
            .filter(Track.camera_id == cam.id)
            .order_by(Track.last_seen.desc())
            .limit(1)
            .all()
        )
        if recent_tracks:
            tr = recent_tracks[0]
            t_str = tr.last_seen.strftime("%H:%M:%S") if tr.last_seen else now.strftime("%H:%M:%S")
            status_badge = (
                '<span style="background:#15803d; padding:2px 8px; border-radius:4px; '
                'font-size:12px; color:#dcfce7;">TRACK LOGGED</span>'
            )
        else:
            t_str = "—"
            status_badge = (
                '<span style="background:#374151; padding:2px 8px; border-radius:4px; '
                'font-size:12px; color:#9ca3af;">NO TRACKS</span>'
            )

        lat = getattr(cam, "latitude", 21.2000)
        lng = getattr(cam, "longitude", 72.8300)
        timeline_rows += f"""
        <tr>
            <td style="padding:10px; border:1px solid #334155; text-align:center;">{idx + 1}</td>
            <td style="padding:10px; border:1px solid #334155; font-family:monospace;">{t_str}</td>
            <td style="padding:10px; border:1px solid #334155;"><strong>{cam.name}</strong> ({cam.location})</td>
            <td style="padding:10px; border:1px solid #334155; font-family:monospace;">{lat:.4f}° N, {lng:.4f}° E</td>
            <td style="padding:10px; border:1px solid #334155;">{status_badge}</td>
        </tr>
        """

    # Count alerts related to this export (if export_id maps to an alert ID)
    alert_count = 0
    try:
        alert_id_int = int(export_id)
        alert = db.query(Alert).filter(Alert.id == alert_id_int).first()
        if alert:
            alert_count = 1
    except (ValueError, TypeError):
        alert_count = db.query(Alert).count()

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Police FIR Evidence Annexure - {case_num}</title>
        <style>
            body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 40px; }}
            .container {{ max-width: 900px; margin: 0 auto; background: #1e293b; padding: 40px; border-radius: 12px; border: 1px solid #334155; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }}
            .header {{ text-align: center; border-bottom: 2px solid #0284c7; padding-bottom: 20px; margin-bottom: 30px; }}
            .badge {{ background: #0284c7; color: white; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: bold; text-transform: uppercase; }}
            .meta-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; background: #0f172a; padding: 20px; border-radius: 8px; border: 1px solid #334155; }}
            .meta-item label {{ color: #94a3b8; font-size: 12px; display: block; text-transform: uppercase; letter-spacing: 0.5px; }}
            .meta-item span {{ font-size: 16px; font-weight: 600; color: #38bdf8; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }}
            th {{ background: #0f172a; color: #94a3b8; text-align: left; padding: 12px; border: 1px solid #334155; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }}
            .signature-box {{ margin-top: 40px; padding: 20px; background: #0f172a; border-radius: 8px; border: 1px solid #334155; font-family: monospace; font-size: 12px; color: #a855f7; word-break: break-all; }}
            .notice-box {{ margin-top: 12px; padding: 12px 16px; background: #1c2a42; border: 1px solid #3b82f6; border-radius: 6px; font-size: 12px; color: #93c5fd; font-family: sans-serif; }}
            .btn-print {{ background: #0284c7; color: white; border: none; padding: 10px 24px; border-radius: 6px; font-weight: bold; cursor: pointer; float: right; }}
            .btn-print:hover {{ background: #0369a1; }}
            @media print {{
                body {{ background: white; color: black; padding: 0; }}
                .container {{ border: none; box-shadow: none; padding: 0; background: white; color: black; }}
                .meta-grid, th, .signature-box {{ background: #f1f5f9; color: black; border-color: #cbd5e1; }}
                .meta-item span {{ color: #0284c7; }}
                .btn-print {{ display: none; }}
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <button class="btn-print" onclick="window.print()">🖨️ Print Formal FIR Annexure</button>
            <div class="header">
                <span class="badge">SURAT CITY POLICE • COMMAND &amp; CONTROL VMS</span>
                <h1 style="margin: 10px 0 5px 0; letter-spacing: 0.5px;">FIRST INFORMATION REPORT (FIR)</h1>
                <p style="color: #94a3b8; margin: 0; font-size: 14px;">Automated Video Evidence &amp; Digital Chain-of-Custody Dossier</p>
            </div>

            <div class="meta-grid">
                <div class="meta-item"><label>Case / FIR Reference No.</label><span>{case_num}</span></div>
                <div class="meta-item"><label>Generated Timestamp (UTC)</label><span>{now_str}</span></div>
                <div class="meta-item"><label>Generated By (VMS User)</label><span>{user.username.upper()}</span></div>
                <div class="meta-item"><label>Total Alerts in Record</label><span>{alert_count} Event(s)</span></div>
                <div class="meta-item"><label>Audit Log Reference</label><span>AuditLog #{audit_id}</span></div>
                <div class="meta-item"><label>Legal Framework</label><span>DPDP Act 2023 | IT Act S.79</span></div>
            </div>

            <h3 style="border-bottom: 1px solid #334155; padding-bottom: 8px; color: #f8fafc;">1. Incident Summary</h3>
            <p style="color: #cbd5e1; font-size: 14px; line-height: 1.6;">
                This report was automatically generated by the VMS Pro Command &amp; Control System
                for Case Reference <strong>{case_num}</strong>. The trajectory evidence below reflects
                real-time track data logged by the AI inference pipeline across connected camera endpoints.
                Each timeline entry shows the last confirmed detection timestamp per camera.
            </p>

            <h3 style="border-bottom: 1px solid #334155; padding-bottom: 8px; color: #f8fafc; margin-top: 30px;">2. Multi-Camera Chronological Trajectory Evidence Log</h3>
            <table>
                <thead>
                    <tr>
                        <th style="width: 50px;">Seq</th>
                        <th style="width: 100px;">Last Seen</th>
                        <th>Camera Junction / Location</th>
                        <th style="width: 160px;">GIS Coordinates</th>
                        <th style="width: 120px;">Track Status</th>
                    </tr>
                </thead>
                <tbody>
                    {timeline_rows}
                </tbody>
            </table>

            <h3 style="border-bottom: 1px solid #334155; padding-bottom: 8px; color: #f8fafc; margin-top: 30px;">3. Cryptographic Integrity Signature</h3>
            <div class="signature-box">
                <div><strong>SHA-256 REPORT INTEGRITY HASH:</strong> {integrity_hash}</div>
                <div style="margin-top:8px;"><strong>HASH INPUT:</strong> CASE_NUM | OFFICER | ISO_TIMESTAMP | AUDIT_LOG_ID</div>
                <div style="margin-top:8px;"><strong>AUDIT LOG ENTRY:</strong> AuditLog #{audit_id} — Server-internal record. Immutable after commit.</div>
                <div style="margin-top:8px;"><strong>TIMESTAMP SOURCE:</strong> VMS Server UTC clock (NTP-synced system time)</div>
            </div>
            <div class="notice-box">
                ℹ️ <strong>Integrity Notice:</strong> This hash is computed from real report metadata (case number, officer
                username, UTC timestamp, audit log ID). It provides internal tamper-evidence but is NOT an RFC-3161
                third-party timestamping authority (TSA) signature. For court-admissible external timestamping,
                submit the export ZIP to an accredited TSA separately.
            </div>

            <div style="margin-top: 40px; text-align: center; color: #64748b; font-size: 12px; border-top: 1px solid #334155; padding-top: 20px;">
                CONFIDENTIAL — FOR OFFICIAL POLICE INVESTIGATION USE ONLY • GENERATED BY SYBAU VMS PRO SYSTEM<br>
                Document generated: {now_str} | Case: {case_num} | Officer: {user.username}
            </div>
        </div>
    </body>
    </html>
    """
    return HTMLResponse(content=html_content)
